book_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('users/', include('users.urls')),
]

books/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
    BookDetailView,
    BooksListView,
    CategoryBookListView,
    confirm_rent_view,
    contact_form,
    HomeListView,
    login_to_comment_redirect,
    rate_book_view,
    return_book_view,
    rent_book_view,
    SearchBookListView,
    ExpiredBooks,
)


urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('search-book-results/', SearchBookListView.as_view(), name='search'),
    path('books', BooksListView.as_view(), name='books'),
    path('expired', ExpiredBooks.as_view(), name='expired'),
    path('book/<slug:slug>',
         BookDetailView.as_view(), name='bookDetail'),
    path('confirm-rent-a-book/<slug:slug>',
         confirm_rent_view, name="confirm_rent_view"),
    path('book/rent-book/<slug:slug>', rent_book_view, name='rent_book'),
    path('book/return-book/<slug:slug>', return_book_view, name='return_book'),
    path('books-by-category/<slug:slug>',
         CategoryBookListView.as_view(), name='category_books_view'),
    path('book/<slug:slug>/<rating>', rate_book_view, name='rate_book'),
    path('contact', contact_form, name='contact'),
    path('redirect-to-detail/<slug:slug>', login_to_comment_redirect,
         name='login_to_comment_redirect')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from PIL import Image
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify

# Create your models here.


class Category(models.Model):
    category = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.category

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"


class Book(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(unique=True, allow_unicode=True)
    description = models.TextField(max_length=1000, default="About book")
    image = models.ImageField(
        default='default_book.png', upload_to='books_pics')
    author = models.CharField(max_length=100)
    book_amount = models.IntegerField()
    publish_date = models.DateField()
    number_of_pages = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    last_rating = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    @property
    def actual_rating(self):
        list_of_stars = []
        for star in range(self.last_rating):
            list_of_stars.append(star)
        return list_of_stars

    @property
    def calc_rating(self):
        ratings = BookReview.objects.filter(book=self)
        if ratings:
            result = 0
            for rating in ratings:
                result += rating.rating
            result = int(result / len(ratings))
            return result
        else:
            return 0

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 200 or img.width > 200:
            output_size = (150, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class BookRentHistory(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.PROTECT, editable=False)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, editable=False, related_name='books')
    rent_date = models.DateField(auto_now_add=True, editable=False)
    back_date = models.DateField(
        default=datetime.now()+timedelta(days=30))

    @property
    def how_many_days(self):
        return str(self.back_date - datetime.now().date())[:3]


class BookReview(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    rating = models.IntegerField()


class BookComment(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.CharField(max_length=300)


class InBoxMessages(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    message = models.TextField(max_length=500)

    def __str__(self):
        return f'Message from {self.name}'

books/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(label='Name')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Message', widget=forms.Textarea())


class CommentForm(forms.Form):
    text = forms.CharField(label='Add comment:', widget=forms.Textarea(
        attrs={'rows': 4, 'cols': 15}))

books/views.py
from django.shortcuts import render, redirect, reverse
from django.http import Http404, HttpResponseForbidden
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    DetailView,
    FormView,
    ListView,
    TemplateView,
    UpdateView)

from .forms import (
    ContactForm,
    CommentForm)
from .models import (
    Book,
    BookComment,
    BookRentHistory,
    BookReview,
    Category,
    InBoxMessages,
)
# Create your views here.

class ExpiredBooks(ListView):
    model = 'BookRentHistory', 'Book'
    template_name ='books/book_expired.html'

    def get_queryset(self):
        return BookRentHistory.objects.all()

class HomeListView(ListView):
    template_name = 'books/home.html'
    model = Book

    def get_queryset(self):
        queryset = super(HomeListView, self).get_queryset()
        return queryset.all().order_by('id')


class BooksListView(ListView):
    template_name = 'books/books.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super(BooksListView, self).get_context_data(**kwargs)
        context.update({
            'top_3_books': Book.objects.order_by('-last_rating')[:3],
            'most_reviews': Book.objects.annotate(reviews_count=Count('reviews')).order_by('-reviews_count')[:3],
            'most_comments': Book.objects.annotate(comments_count=Count('comments')).order_by('-comments_count')[:3],
        })
        return context

    def get_queryset(self):
        return Book.objects.order_by('id')


class SearchBookListView(ListView):
    template_name = "books/book_search_result.html"
    model = Book

    def get_queryset(self):
        queryset = super(SearchBookListView, self).get_queryset()
        q = self.request.GET.get("q")
        if q:
            books_by_title = queryset.filter(title__icontains=q)
            books_by_author = queryset.filter(author__icontains=q)
            return books_by_author | books_by_title
        return queryset


class BookDetailView(FormMixin, DetailView):
    model = Book
    form_class = CommentForm

    def get_success_url(self):
        return reverse('bookDetail', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['comments'] = BookComment.objects.filter(
            book=self.object).order_by('-id')
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        b = self.get_object()
        text = form.cleaned_data['text']
        new_comment = BookComment(text=text, book=b, user=self.request.user)
        new_comment.save()
        messages.success(self.request, "Your comment is added, thank you")
        return super().form_valid(form)


@login_required(login_url='login')
def login_to_comment_redirect(request, slug):
    return redirect('bookDetail', slug=slug)


@login_required(login_url='login')
def confirm_rent_view(request, slug):
    try:
        b = Book.objects.get(slug=slug)
        if b.book_amount <= 0:
            messages.warning(
                request, f'You cant rent this book')
            return redirect('bookDetail', slug=b.slug)
    except Book.DoesNotExist:
        raise Http404("We ont have this book")
    return render(request, 'books/confirm_rent_view.html', {'book': b})


@login_required(login_url='login')
def rent_book_view(request, slug):
    try:
        b = Book.objects.get(slug=slug)
        if b:
            if b.book_amount > 0:
                b.book_amount -= 1
                b.save()
                log_history = BookRentHistory(user=request.user, book=b)
                log_history.save()
                messages.success(
                    request, f'대여 성공: {b.title}')
            else:
                messages.warning(
                    request, f'대여 실패')
                return redirect('bookDetail', slug=b.slug)
    except Book.DoesNotExist:
        raise Http404("Book is unavailable")
    return redirect('UserProfile')


@login_required(login_url='login')
def return_book_view(request, slug):
    try:
        b = Book.objects.filter(slug=slug)[0]
        if b:
            b.book_amount += 1
            b.save()
            log_history = BookRentHistory.objects.filter(book=b)[0]
            log_history.delete()
            messages.success(
                request, f'성공적으로 반환되었습니다.: {b.title}')
        else:
            messages.warning(
                request, f'Error occurs, sorry')
            return redirect('UserProfile')
    except Book.DoesNotExist:
        raise Http404("Book is unavailable now ")
    return redirect('UserProfile')


class CategoryBookListView(ListView):
    template_name = "books/books_by_category.html"
    model = Book

    def get_queryset(self):
        category = Category.objects.get(slug=self.kwargs['slug'])
        return Book.objects.filter(category=category)


@login_required(login_url='login')
def rate_book_view(request, slug, rating):
    try:
        b = Book.objects.get(slug=slug)
        if b and not(BookReview.objects.filter(user=request.user).filter(book=b)):
            review = BookReview(book=b, user=request.user, rating=rating)
            review.save()
            b.last_rating = b.calc_rating
            b.save()
            messages.success(
                request, f'You rated a book: {b.title}')

        else:
            messages.warning(
                request, f'You already rated this book')
        return redirect('bookDetail', slug=b.slug)
    except Book.DoesNotExist:
        raise Http404("Book is unavailable")
    return redirect('bookDetail', slug=b.slug)


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            new_message = InBoxMessages()
            new_message.name = name
            new_message.email = email
            new_message.message = message
            new_message.save()
            messages.success(request, "Your message is sent")
            return redirect('home')
    if request.user.is_authenticated:
        form = ContactForm()
        form.fields['name'].initial = request.user.username
        form.fields['email'].initial = request.user.email
        form.fields['message'].widget.attrs['placeholder'] = 'Write your message here'
        form.fields['name'].label = 'Login'
        form.fields['name'].widget.attrs['readonly'] = True
        form.fields['email'].widget.attrs['readonly'] = True
        return render(request, 'books/contact.html', {'form': form})
    else:
        form = ContactForm()
        form.fields['name'].widget.attrs['placeholder'] = 'Your name'
        form.fields['email'].widget.attrs['placeholder'] = 'Your email'
        form.fields['message'].widget.attrs['placeholder'] = 'Write your message here'
        return render(request, 'books/contact.html', {'form': form})

books/templates/books/book_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<div class="row">
    <div class="col-md-4 bookDetailLeftSide">
        <img class="bookImage" src="{{ book.image.url }}" alt=""> <br>
        <!-- <img class="bookImage" src="{% static 'icons/book2.jpg' %}" alt=""> <br> -->
        {% if book.actual_rating %}
        {% for rate in book.actual_rating %}
        <span class="fa fa-star checked"></span>
        {% endfor %}
        <br>
        평점 등록 개수({{ book.reviews.count }})<br>
        {% else %}
        <br>
        <h6>평점 없음</h6>
        {% endif %}
        평점:
        <a href="{% url 'rate_book' slug=book.slug rating=1 %}">①</a>
        <a href="{% url 'rate_book' slug=book.slug rating=2 %}">②</a>
        <a href="{% url 'rate_book' slug=book.slug rating=3 %}">③</a>
        <a href="{% url 'rate_book' slug=book.slug rating=4 %}">④</a>
        <a href="{% url 'rate_book' slug=book.slug rating=5 %}">⑤</a> <br>
        <a href="#commentBox">댓글 수 ({{ book.comments.count }})</a>
        {% if book.book_amount > 0 %}
        <h5><strong>현재 남은 수량 :</strong> {{ book.book_amount }}</h5>
        {% if user.is_authenticated %}
        <a href="{% url 'confirm_rent_view' slug=book.slug %}"><button class="btn btn-primary btn-xs">대여</button></a>
        {% else %}
        <a href="{% url 'confirm_rent_view' slug=book.slug %}"><button class="btn btn-primary btn-xs">대여를 위한 로그인
                </button></a>
        {% endif %}
        {% else %}
        <p><strong>현재 남은 수량 </strong></p> <h5 style="font-size:20px;color:red;">없음</h5>
        {% endif %} <br>
    </div>
    <div class="col-md-8">
        <h5><strong>{{ book.title }}</strong> </h5>
        <h5><strong>저자:</strong> {{ book.author }}</h5>
        <h5><strong>카테고리:</strong> {{ book.category }}</h5>
        <h6><strong>설명:</strong> </h6>
        <p> {{ book.description }}</p>
        <hr class="my-4">
        <div id="commentBox">
            {% if user.is_authenticated %}
            <form method="post" class="formsWidth">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">댓글 등록</button>
            </form>
            {% else %}
            <a href="{% url 'login_to_comment_redirect' slug=book.slug %}"><button class="btn btn-primary btn-xs">댓글
                    등록 (로그인)</button></a>
            {% endif %}

            {% if comments %}
            <br> <br>
            <h6>댓글({{ book.comments.count }}):</h6>
            {% for comment in comments %}
            <div>
                <h6><strong>{{ comment.user.username }}</strong></h6>
                <h6 class="comment_text">{{ comment.text }}</h6>
            </div>
            <hr class="my-4">
            {% endfor %}
            {% else %}
            <h6>댓글 없음</h6>

            {% endif %}
        </div>
    </div>



</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>








{% endblock content %}

books/templates/books/book_expired.html
{% extends "base.html" %}
{% block content %}
<div class="row">

    <div class="col-md-9">
        <h2>전체 대여 목록:</h2>
        <table style="width:100%" id="books">
            <tr>
                <th>대여자</th>
                <th>도서명</th>
                <th>대여일</th>
                <th>반환기일</th>
                <th>남은일수</th>
                <th>상태</th>
            </tr>

            {% for book in bookrenthistory_list %}
            <!-- <h1> test </h -->
            <tr>
                <td>{{ book.user }}</td>
                <td>{{ book.book.title }}</td>
                <td>{{ book.rent_date|date:"M.d Y" }}</td>
                <td>{{ book.back_date|date:"M.d Y" }}</td>
                <td>{{ book.how_many_days }}</td>
                {% if '-' in book.how_many_days  %}
                <td style="color:red"> 연체 </td>
                {% else %}
                <td style="color:blue"> 정상 </td> 
                {% endif %}
                
            </tr>
            {% endfor %}
        </table>

    </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


{% endblock content %}

books/templates/books/book_search_result.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h2>검색결과: "{{ request.GET.q }}":</h2>
<div class="row lastBooksContainer">
    {% if book_list %}
    {% for book in book_list %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <img class="book_image" src="{{ book.image.url }}" alt="Book image">
            <!-- <img class="book_image" src="{% static 'icons/book2.jpg' %}" alt="Book image">             -->
            <h5>{{ book.title }}</h5>
            <h6>{{ book.author }}</h6>
            {% if book.actual_rating %}
            {% for rate in book.actual_rating %}
            <span class="fa fa-star checked"></span>
            {% endfor %} <br>
            {% else %}
            <h6>평점 등록 없음</h6>
            {% endif %}
            <a href="{% url 'bookDetail' slug=book.slug %}"><button class="btn btn-primary btn-xs">도서 세부사항</button></a>
        </div>

    </div>
    {% endfor %}
    {% else %}
    <h5 style="margin-left:30px;"> 그런 책은 없네요 ㅠㅠ</h5>
    {% endif %}


</div>
{% endblock content %}

books/templates/books/books.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<p>
    <h5>도서 검색</h5>
    <form class="searchForm" action="{% url 'search' %}" method=" GET">
        <div class="form-group row">
            <input class="form-control col-md-7" required="required" name="q" type="text" placeholder="도서명이나 저자명을 입력하세요">
            <span class="col-md-1"></span>
            <button type="submit" class="btn btn-primary form-control col-md-2">검색가즈아</button>
        </div>
    </form>
</p>
<hr class="my-4">
<!-- <h3>Best rated books:</h3>
<div class="row lastBooksContainer">
    {% for book in top_3_books %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <img class="book_image" src="{{ book.image.url }}" alt="Book image">
            <h5>{{ book.title }}</h5>
            <h6>{{ book.author }}</h6>
            {% if book.actual_rating %}
            {% for rate in book.actual_rating %}
            <span class="fa fa-star checked"></span>
            {% endfor %} <br>
            {% else %}
            <h6>Nobody rated</h6>
            {% endif %}
            <a href="{% url 'bookDetail' slug=book.slug %}"><button class="btn btn-primary btn-xs">Book details</button></a>
        </div>
    </div>
    {% endfor %}
</div>
<h3>Most review books:</h3>
<div class="row lastBooksContainer">
    {% for book in most_reviews %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <img class="book_image" src="{{ book.image.url }}" alt="Book image">
            <h5>{{ book.title }}</h5>
            <h6>{{ book.author }}</h6>
            {% if book.actual_rating %}
            {% for rate in book.actual_rating %}
            <span class="fa fa-star checked"></span>
            {% endfor %} <br>
            {% else %}
            <h6>Nobody rated</h6>
            {% endif %}
            <a href="{% url 'bookDetail' slug=book.slug %}"><button class="btn btn-primary btn-xs">Book details</button></a>
        </div>
    </div>
    {% endfor %}
</div>
<h3>Most comment books:</h3>
<div class="row lastBooksContainer">
    {% for book in most_comments %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <img class="book_image" src="{{ book.image.url }}" alt="Book image">
            <h5>{{ book.title }}</h5>
            <h6>{{ book.author }}</h6>
            {% if book.actual_rating %}
            {% for rate in book.actual_rating %}
            <span class="fa fa-star checked"></span>
            {% endfor %} <br>
            {% else %}
            <h6>Nobody rated</h6>
            {% endif %}
            <a href="{% url 'bookDetail' slug=book.slug %}"><button class="btn btn-primary btn-xs">Book details</button></a>
        </div>
    </div>
    {% endfor %}
</div> -->
<h3>도서 목록</h3>
<div class="row lastBooksContainer">
    {% for book in book_list %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <img class="book_image" src="{{ book.image.url }}" alt="Book image">
            <!-- <img class="book_image" src="{% static 'icons/book2.jpg' %}" alt="Book image"> -->
            <h5>{{ book.title }}</h5>
            <h6>{{ book.author }}</h6>
            {% if book.actual_rating %}
            {% for rate in book.actual_rating %}
            <span class="fa fa-star checked"></span>
            {% endfor %} <br>
            {% else %}
            <h6>평점 없음</h6>
            {% endif %}
            <a href="{% url 'bookDetail' slug=book.slug %}"><button class="btn btn-primary btn-xs">선택</button></a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

books/templates/books/books_by_category.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h2>해당 카테고리 내 도서:{{ book_list.first.category }}</h2>
<div class="row lastBooksContainer">
    {% for book in book_list %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <!-- <img class="book_image" src="{% static 'icons/book2.jpg' %}" alt="Book image"> -->
            <img class="book_image" src="{{ book.image.url }}" alt="Book image">
            <h5>{{ book.title }}</h5>
            <h6>{{ book.author }}</h6>
            {% if book.actual_rating %}
            {% for rate in book.actual_rating %}
            <span class="fa fa-star checked"></span>
            {% endfor %} <br>
            {% else %}
            <h6>평점 등록 없음</h6>
            {% endif %}
            <a href="{% url 'bookDetail' slug=book.slug %}"><button class="btn btn-primary btn-xs">도서 세부사항</button></a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

books/templates/books/confirm_rent_view.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<h3>진짜 대여하시겠습니까? </h3>
<img src="{{ book.image.url }}" class="bookImage" alt="">
<h5><strong>도서명:</strong> {{ book.title }}</h5>
<h5><strong>저자:</strong> {{ book.author }}</h5>
<a href="{% url 'rent_book' slug=book.slug %}"><button class="btn btn-success btn-xs">네</button></a>
<a href="{% url 'bookDetail' slug=book.slug %}"><button class="btn btn-info btn-xs">아니요</button></a>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

books/templates/books/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post" class="formsWidth">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">전송</button>
</form>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

books/templates/books/home.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="jumbotron">
    <h1 class="display-4">환영합니다</h1>
    <p class="lead">IT기술혁신센터 직원 전용 자율형도서관</p>
    <hr class="my-4">
    <p>
        <h5>도서 검색</h5>
        <form class="searchForm" action="{% url 'search' %}" method=" GET">
            <div class="form-group row">
                <input class="form-control col-md-7" required="required" name="q" type="text" placeholder="도서명이나 저자명 입력">
                <span class="col-md-1"></span>
                <button type="submit" class="btn btn-primary form-control col-md-2">검색가즈아</button>
            </div>
        </form>

    </p>
</div>
<hr class="my-4">
<h2>최근 추가된 도서:</h2>
<div class="row lastBooksContainer">
    {% for book in book_list %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <!-- <img class="book_image" src="{% static 'icons/book2.jpg' %}" alt="Book image"> -->
            <img class="book_image" src="{{ book.image.url }}" alt="Book image">

            <h5>{{ book.title }}</h5>
            <h6>{{ book.author }}</h6>
            {% if book.actual_rating %}
            {% for rate in book.actual_rating %}
            <span class="fa fa-star checked"></span>
            {% endfor %} <br>
            {% else %}
            <h6>평점 없음</h6>
            {% endif %}

            <a href="{% url 'bookDetail' slug=book.slug %}"><button class="btn btn-primary btn-xs">선택</button></a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}